name: almetlaa
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  get: ^4.7.2
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  panorama: ^0.4.1
  get_storage: ^2.1.1
  flutter_share: ^2.0.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_countdown_timer: ^4.1.0
  socket_io_client: ^3.0.2
  image_gallery_saver: ^2.0.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pdf: ^3.11.3
  pdfx: ^2.8.0
  pretty_dio_logger: ^1.4.0

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: amarai
      fonts:
        - asset: assets/fonts/amarai.ttf
