name: baiti
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  better_player_plus: ^1.0.8
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.0.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  pin_code_fields: ^8.0.1
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  socket_io_client: ^3.0.2
  url_launcher: ^6.3.1
  youtube_player_embed: ^1.6.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: amarai
      fonts:
        - asset: assets/fonts/amarai.ttf
